# Site settings
title: Carlos Blog
SEOTitle: Carlos的博客 | Carlos Blog
header-img: img/home-bg.jpg
email: carlos.w.0713@oulook.com
description: "Every failure is leading towards success."
keyword: "carlos, carlos Blog, carlos的博客, carlos, github, gitee, csdn, 测试"
url: "http://carlosw0713.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/carlosw0713/carlosw0713.github.io.git" # you code repository

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username: carlos111
# zhihu_username: carlos1
github_username: carlosw0713
gitee_username: carlosw0713
csdn_username: alnawang
# twitter_username: carlos1
#facebook_username:  carlos1
#linkedin_username:  carlos1

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: hux
disqus_username: Carlos11

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me ## 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
ga_domain: auto

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "乐观的悲观主义者 <br> Email:Carlos.w.0713@outlook.com  <br> Wechat:hqq51921"
# sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: /img/about-Carlos1.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


#debug模式
jekyll: true

# Friends
# friends:
#   [
#     { title: "乱序（Midare）", href: "http://mida.re/" },
#     { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#     { title: "Kun Qian", href: "http://kunq.me" },
#     { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#     { title: "SmdCn", href: "http://blog.smdcn.net" },
#     { title: "JiyinYiyong", href: "http://tiye.me/" },
#     { title: "DHong Say", href: "http://dhong.co" },
#     { title: "尹峰以为", href: "http://ingf.github.io/" },
#   ]

friends:
  [
    { title: "Carlos", href: "https://github.com/carlosw0713" },
    { title: "Gtihub", href: "https://github.com/carlosw0713" },
    { title: "Gitee", href: "https://gitee.com/carlos_w_0713" },
    { title: "CSDN", href: "https://blog.csdn.net/alnawang" },
    { title: "篮球", href: "https://baike.baidu.com/item/%E7%A7%91%E6%AF%94%C2%B7%E5%B8%83%E8%8E%B1%E6%81%A9%E7%89%B9/318773" },
    { title: "漫画&动漫", href: "https://zhuanlan.zhihu.com/p/584071572" },
    { title: "ChatGTP", href: "https://c.binjie.fun/" },
  ]

gems:
- jekyll-mermaid